### ISSUE TITLE
Purpose of this project

### ISSUE THREAD

**Issue by GeorgeS2019** [V-Sekai/godot-humanoid-project#1]
> a file which contains **constants** used by **Unity's animation system**. The usecase is experimenting with **network serialization**

https://discord.com/channels/471446618156040210/590513531313586178/1280659335894274346

https://github.com/V-Sekai/godot-humanoid-project/tree/main/addons/humanoid

**Comment by fire** [comment]
What is needed to be done here?

**Comment by GeorgeS2019** [comment]
Here is only 0.1%

**Comment by fire** [comment]
What does that mean?

**Comment by fire** [comment]
The purpose of this project is post work in progress and share code with the Basis project.
